<?php

namespace Database\Seeders;

use App\Models\Driver;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DriverSeeder extends Seeder
{
    public function run(): void
    {
        $drivers = [
            // F1
            // Red Bull Racing
            [
                'first_name' => 'Max',
                'last_name' => 'Verstappen',
                'birth_date' => '1997-09-30',
                'birth_country' => 'Netherlands',
                'vehicle_number' => 1,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/5/58/Max_Verstappen_2017_Malaysia_2.jpg',
                'active' => true,
                'team_id' => 1,
            ],
            [
                'first_name' => 'Liam',
                'last_name' => 'Lawson',
                'birth_date' => '2002-02-11',
                'birth_country' => 'New Zealand',
                'vehicle_number' => 30,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Liam_Lawson_2022.jpg',
                'active' => true,
                'team_id' => 1,
            ],
            // Mercedes
            [
                'first_name' => 'George',
                'last_name' => 'Russell',
                'birth_date' => '1998-02-15',
                'birth_country' => 'United Kingdom',
                'vehicle_number' => 63,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/4/4f/George_Russell_2020_Tuscany.jpg',
                'active' => true,
                'team_id' => 2,
            ],
            [
                'first_name' => 'Andrea Kimi',
                'last_name' => 'Antonelli',
                'birth_date' => '2006-08-25',
                'birth_country' => 'Italy',
                'vehicle_number' => 12,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Andrea_Kimi_Antonelli_2023.jpg',
                'active' => true,
                'team_id' => 2,
            ],
            // Ferrari
            [
                'first_name' => 'Charles',
                'last_name' => 'Leclerc',
                'birth_date' => '1997-10-16',
                'birth_country' => 'Monaco',
                'vehicle_number' => 16,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Charles_Leclerc_2019.jpg',
                'active' => true,
                'team_id' => 3,
            ],
            [
                'first_name' => 'Lewis',
                'last_name' => 'Hamilton',
                'birth_date' => '1985-01-07',
                'birth_country' => 'United Kingdom',
                'vehicle_number' => 44,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Lewis_Hamilton_2016_Malaysia_2.jpg',
                'active' => true,
                'team_id' => 3,
            ],
            // McLaren
            [
                'first_name' => 'Lando',
                'last_name' => 'Norris',
                'birth_date' => '1999-11-13',
                'birth_country' => 'United Kingdom',
                'vehicle_number' => 4,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Lando_Norris_2019.jpg',
                'active' => true,
                'team_id' => 4,
            ],
            [
                'first_name' => 'Oscar',
                'last_name' => 'Piastri',
                'birth_date' => '2001-04-06',
                'birth_country' => 'Australia',
                'vehicle_number' => 81,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Oscar_Piastri_2022.jpg',
                'active' => true,
                'team_id' => 4,
            ],
            // Aston Martin
            [
                'first_name' => 'Fernando',
                'last_name' => 'Alonso',
                'birth_date' => '1981-07-29',
                'birth_country' => 'Spain',
                'vehicle_number' => 14,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Fernando_Alonso_2016_Malaysia_1.jpg',
                'active' => true,
                'team_id' => 5,
            ],
            [
                'first_name' => 'Lance',
                'last_name' => 'Stroll',
                'birth_date' => '1998-10-29',
                'birth_country' => 'Canada',
                'vehicle_number' => 18,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Lance_Stroll_2017_Malaysia_1.jpg',
                'active' => true,
                'team_id' => 5,
            ],
            // Alpine
            [
                'first_name' => 'Pierre',
                'last_name' => 'Gasly',
                'birth_date' => '1996-02-07',
                'birth_country' => 'France',
                'vehicle_number' => 10,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Pierre_Gasly_2019.jpg',
                'active' => true,
                'team_id' => 6,
            ],
            [
                'first_name' => 'Jack',
                'last_name' => 'Doohan',
                'birth_date' => '2003-01-20',
                'birth_country' => 'Australia',
                'vehicle_number' => 7,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Jack_Doohan_2022.jpg',
                'active' => true,
                'team_id' => 6,
            ],
            // Williams
            [
                'first_name' => 'Alex',
                'last_name' => 'Albon',
                'birth_date' => '1996-03-23',
                'birth_country' => 'Thailand',
                'vehicle_number' => 23,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Alexander_Albon_2019.jpg',
                'active' => true,
                'team_id' => 7,
            ],
            [
                'first_name' => 'Logan',
                'last_name' => 'Sargeant',
                'birth_date' => '2000-12-31',
                'birth_country' => 'United States',
                'vehicle_number' => 2,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Logan_Sargeant_2022.jpg',
                'active' => true,
                'team_id' => 7,
            ],
            // Stake F1 (Sauber)
            [
                'first_name' => 'Valtteri',
                'last_name' => 'Bottas',
                'birth_date' => '1989-08-28',
                'birth_country' => 'Finland',
                'vehicle_number' => 77,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Valtteri_Bottas_2017_Malaysia_2.jpg',
                'active' => true,
                'team_id' => 8,
            ],
            [
                'first_name' => 'Zhou',
                'last_name' => 'Guanyu',
                'birth_date' => '1999-05-30',
                'birth_country' => 'China',
                'vehicle_number' => 24,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Zhou_Guanyu_2022.jpg',
                'active' => true,
                'team_id' => 8,
            ],
            // Visa Cash App RB (ex-AlphaTauri)
            [
                'first_name' => 'Yuki',
                'last_name' => 'Tsunoda',
                'birth_date' => '2000-05-11',
                'birth_country' => 'Japan',
                'vehicle_number' => 22,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/3/34/Yuki_Tsunoda_2022.jpg',
                'active' => true,
                'team_id' => 9,
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Ricciardo',
                'birth_date' => '1989-07-01',
                'birth_country' => 'Australia',
                'vehicle_number' => 3,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Daniel_Ricciardo_2016_Malaysia_3.jpg',
                'active' => true,
                'team_id' => 9,
            ],
            // Haas
            [
                'first_name' => 'Kevin',
                'last_name' => 'Magnussen',
                'birth_date' => '1992-10-05',
                'birth_country' => 'Denmark',
                'vehicle_number' => 20,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Kevin_Magnussen_2017_Malaysia.jpg',
                'active' => true,
                'team_id' => 10,
            ],
            [
                'first_name' => 'Nico',
                'last_name' => 'Hülkenberg',
                'birth_date' => '1987-08-19',
                'birth_country' => 'Germany',
                'vehicle_number' => 27,
                'profile_image' => 'https://upload.wikimedia.org/wikipedia/commons/8/88/Nico_Hulkenberg_2016_Malaysia.jpg',
                'active' => true,
                'team_id' => 10,
            ],
            [
                'first_name' => 'Francesco',
                'last_name' => 'Bagnaia',
                'birth_date' => '1997-01-14',
                'birth_country' => 'Italy',
                'vehicle_number' => 63,
                'profile_image' => null,
                'active' => true,
                'team_id' => 11,
            ],
            [
                'first_name' => 'Marc',
                'last_name' => 'Márquez',
                'birth_date' => '1993-02-17',
                'birth_country' => 'Spain',
                'vehicle_number' => 93,
                'profile_image' => null,
                'active' => true,
                'team_id' => 11,
            ],
            [
                'first_name' => 'Jorge',
                'last_name' => 'Martín',
                'birth_date' => '1998-01-29',
                'birth_country' => 'Spain',
                'vehicle_number' => 1,
                'profile_image' => null,
                'active' => true,
                'team_id' => 12,
            ],
            [
                'first_name' => 'Marco',
                'last_name' => 'Bezzecchi',
                'birth_date' => '1998-11-12',
                'birth_country' => 'Italy',
                'vehicle_number' => 72,
                'profile_image' => null,
                'active' => true,
                'team_id' => 12,
            ],
            [
                'first_name' => 'Fabio',
                'last_name' => 'Quartararo',
                'birth_date' => '1999-04-20',
                'birth_country' => 'France',
                'vehicle_number' => 20,
                'profile_image' => null,
                'active' => true,
                'team_id' => 13,
            ],
            [
                'first_name' => 'Álex',
                'last_name' => 'Rins',
                'birth_date' => '1995-12-08',
                'birth_country' => 'Spain',
                'vehicle_number' => 42,
                'profile_image' => null,
                'active' => true,
                'team_id' => 13,
            ],
            [
                'first_name' => 'Brad',
                'last_name' => 'Binder',
                'birth_date' => '1995-08-11',
                'birth_country' => 'South Africa',
                'vehicle_number' => 33,
                'profile_image' => null,
                'active' => true,
                'team_id' => 14,
            ],
            [
                'first_name' => 'Pedro',
                'last_name' => 'Acosta',
                'birth_date' => '2004-05-25',
                'birth_country' => 'Spain',
                'vehicle_number' => 37,
                'profile_image' => null,
                'active' => true,
                'team_id' => 14,
            ],
            [
                'first_name' => 'Maverick',
                'last_name' => 'Viñales',
                'birth_date' => '1995-01-12',
                'birth_country' => 'Spain',
                'vehicle_number' => 12,
                'profile_image' => null,
                'active' => true,
                'team_id' => 15,
            ],
            [
                'first_name' => 'Enea',
                'last_name' => 'Bastianini',
                'birth_date' => '1997-12-30',
                'birth_country' => 'Italy',
                'vehicle_number' => 23,
                'profile_image' => null,
                'active' => true,
                'team_id' => 15,
            ],
            [
                'first_name' => 'Jack',
                'last_name' => 'Miller',
                'birth_date' => '1995-01-18',
                'birth_country' => 'Australia',
                'vehicle_number' => 43,
                'profile_image' => null,
                'active' => true,
                'team_id' => 16,
            ],
            [
                'first_name' => 'Miguel',
                'last_name' => 'Oliveira',
                'birth_date' => '1995-01-04',
                'birth_country' => 'Portugal',
                'vehicle_number' => 88,
                'profile_image' => null,
                'active' => true,
                'team_id' => 16,
            ],
            [
                'first_name' => 'Álex',
                'last_name' => 'Márquez',
                'birth_date' => '1996-04-23',
                'birth_country' => 'Spain',
                'vehicle_number' => 73,
                'profile_image' => null,
                'active' => true,
                'team_id' => 17,
            ],
            [
                'first_name' => 'Fermín',
                'last_name' => 'Aldeguer',
                'birth_date' => '2005-04-05',
                'birth_country' => 'Spain',
                'vehicle_number' => 54,
                'profile_image' => null,
                'active' => true,
                'team_id' => 17,
            ],
            [
                'first_name' => 'Fabio',
                'last_name' => 'Di Giannantonio',
                'birth_date' => '1998-10-10',
                'birth_country' => 'Italy',
                'vehicle_number' => 49,
                'profile_image' => null,
                'active' => true,
                'team_id' => 18,
            ],
            [
                'first_name' => 'Franco',
                'last_name' => 'Morbidelli',
                'birth_date' => '1994-12-04',
                'birth_country' => 'Italy',
                'vehicle_number' => 21,
                'profile_image' => null,
                'active' => true,
                'team_id' => 18,
            ],
            [
                'first_name' => 'Raúl',
                'last_name' => 'Fernández',
                'birth_date' => '2000-10-23',
                'birth_country' => 'Spain',
                'vehicle_number' => 25,
                'profile_image' => null,
                'active' => true,
                'team_id' => 19,
            ],
            [
                'first_name' => 'Ai',
                'last_name' => 'Ogura',
                'birth_date' => '2001-01-15',
                'birth_country' => 'Japan',
                'vehicle_number' => 79,
                'profile_image' => null,
                'active' => true,
                'team_id' => 19,
            ],
            [
                'first_name' => 'Johann',
                'last_name' => 'Zarco',
                'birth_date' => '1990-07-16',
                'birth_country' => 'France',
                'vehicle_number' => 5,
                'profile_image' => null,
                'active' => true,
                'team_id' => 20,
            ],
            [
                'first_name' => 'Somkiat',
                'last_name' => 'Chantra',
                'birth_date' => '1998-12-15',
                'birth_country' => 'Thailand',
                'vehicle_number' => 35,
                'profile_image' => null,
                'active' => true,
                'team_id' => 20,
            ],
            [
                'first_name' => 'Luca',
                'last_name' => 'Marini',
                'birth_date' => '1997-08-10',
                'birth_country' => 'Italy',
                'vehicle_number' => 10,
                'profile_image' => null,
                'active' => true,
                'team_id' => 21,
            ],
            [
                'first_name' => 'Joan',
                'last_name' => 'Mir',
                'birth_date' => '1997-09-01',
                'birth_country' => 'Spain',
                'vehicle_number' => 36,
                'profile_image' => null,    
                'active' => true,
                'team_id' => 21,
            ],    
        ];

        foreach ($drivers as $driver) {
            Driver::create($driver);
        }
    }
}
