<?php

namespace Database\Seeders;

use App\Models\Driver;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DriverSeeder extends Seeder
{
    public function run(): void
    {
        $drivers = [
            // F1
            // Red Bull Racing
            [
                'first_name' => 'Max',
                'last_name' => 'Verstappen',
                'birth_date' => '1997-09-30',
                'birth_country' => 'Netherlands',
                'vehicle_number' => 1,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS92ZXIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 1,
            ],
            [
                'first_name' => 'Liam',
                'last_name' => 'Lawson',
                'birth_date' => '2002-02-11',
                'birth_country' => 'New Zealand',
                'vehicle_number' => 30,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyMy9kcml2ZXJzL2hlYWRzaG90cy9mMS9sYXcucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 1,
            ],
            // Mercedes
            [
                'first_name' => 'George',
                'last_name' => 'Russell',
                'birth_date' => '1998-02-15',
                'birth_country' => 'United Kingdom',
                'vehicle_number' => 63,
                'profile_image' => 'https://e2.365dm.com/f1/drivers/256x256/h_full_1496.png',
                'active' => true,
                'team_id' => 2,
            ],
            [
                'first_name' => 'Andrea Kimi',
                'last_name' => 'Antonelli',
                'birth_date' => '2006-08-25',
                'birth_country' => 'Italy',
                'vehicle_number' => 12,
                'profile_image' => 'https://images.ctfassets.net/1fvlg6xqnm65/5YiTw6xQHuM94ty9yLDnyk/ff67d40c690940307f48d1b370352577/Kimi_Antonelli.png?w=3840&q=75&fm=webp',
                'active' => true,
                'team_id' => 2,
            ],
            // Ferrari
            [
                'first_name' => 'Charles',
                'last_name' => 'Leclerc',
                'birth_date' => '1997-10-16',
                'birth_country' => 'Monaco',
                'vehicle_number' => 16,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9sZWMucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 3,
            ],
            [
                'first_name' => 'Lewis',
                'last_name' => 'Hamilton',
                'birth_date' => '1985-01-07',
                'birth_country' => 'United Kingdom',
                'vehicle_number' => 44,
                'profile_image' => 'https://sportrenders.com/wp-content/uploads/2024/02/Hamilton-PNG-Ferrari-Render-F1-Sport-Renders.png',
                'active' => true,
                'team_id' => 3,
            ],
            // McLaren
            [
                'first_name' => 'Lando',
                'last_name' => 'Norris',
                'birth_date' => '1999-11-13',
                'birth_country' => 'United Kingdom',
                'vehicle_number' => 4,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyMi9kcml2ZXJzL2hlYWRzaG90cy9mMS9ub3IucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 4,
            ],
            [
                'first_name' => 'Oscar',
                'last_name' => 'Piastri',
                'birth_date' => '2001-04-06',
                'birth_country' => 'Australia',
                'vehicle_number' => 81,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyMy9kcml2ZXJzL2hlYWRzaG90cy9mMS9waWEucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 4,
            ],
            // Aston Martin
            [
                'first_name' => 'Fernando',
                'last_name' => 'Alonso',
                'birth_date' => '1981-07-29',
                'birth_country' => 'Spain',
                'vehicle_number' => 14,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9hbG8ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 5,
            ],
            [
                'first_name' => 'Lance',
                'last_name' => 'Stroll',
                'birth_date' => '1998-10-29',
                'birth_country' => 'Canada',
                'vehicle_number' => 18,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9zdHIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 5,
            ],
            // Alpine
            [
                'first_name' => 'Pierre',
                'last_name' => 'Gasly',
                'birth_date' => '1996-02-07',
                'birth_country' => 'France',
                'vehicle_number' => 10,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9nYXMucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 6,
            ],
            [
                'first_name' => 'Jack',
                'last_name' => 'Doohan',
                'birth_date' => '2003-01-20',
                'birth_country' => 'Australia',
                'vehicle_number' => 7,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS1hZmZpbGlhdGVzL2Rvby5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjUwMH19fQ==',
                'active' => true,
                'team_id' => 6,
            ],
            // Williams
            [
                'first_name' => 'Alex',
                'last_name' => 'Albon',
                'birth_date' => '1996-03-23',
                'birth_country' => 'Thailand',
                'vehicle_number' => 23,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9hbGIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 7,
            ],
            [
                'first_name' => 'Logan',
                'last_name' => 'Sargeant',
                'birth_date' => '2000-12-31',
                'birth_country' => 'United States',
                'vehicle_number' => 2,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyMy9kcml2ZXJzL2hlYWRzaG90cy9mMS9zYXIucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 7,
            ],
            // Stake F1 (Sauber)
            [
                'first_name' => 'Valtteri',
                'last_name' => 'Bottas',
                'birth_date' => '1989-08-28',
                'birth_country' => 'Finland',
                'vehicle_number' => 77,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9ib3QucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 8,
            ],
            [
                'first_name' => 'Zhou',
                'last_name' => 'Guanyu',
                'birth_date' => '1999-05-30',
                'birth_country' => 'China',
                'vehicle_number' => 24,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS96aG8ucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 8,
            ],
            // Visa Cash App RB (ex-AlphaTauri)
            [
                'first_name' => 'Yuki',
                'last_name' => 'Tsunoda',
                'birth_date' => '2000-05-11',
                'birth_country' => 'Japan',
                'vehicle_number' => 22,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyMi9kcml2ZXJzL2hlYWRzaG90cy9mMS90c3UucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 9,
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Ricciardo',
                'birth_date' => '1989-07-01',
                'birth_country' => 'Australia',
                'vehicle_number' => 3,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyNC9kcml2ZXJzL2hlYWRzaG90cy9mMS9yaWMucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 9,
            ],
            // Haas
            [
                'first_name' => 'Kevin',
                'last_name' => 'Magnussen',
                'birth_date' => '1992-10-05',
                'birth_country' => 'Denmark',
                'vehicle_number' => 20,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyMy9kcml2ZXJzL2hlYWRzaG90cy9mMS9tYWcucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 10,
            ],
            [
                'first_name' => 'Nico',
                'last_name' => 'Hülkenberg',
                'birth_date' => '1987-08-19',
                'birth_country' => 'Germany',
                'vehicle_number' => 27,
                'profile_image' => 'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiJmMW1hbmFnZXIvMjAyMy9kcml2ZXJzL2hlYWRzaG90cy9mMS9odWwucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo1MDB9fX0=',
                'active' => true,
                'team_id' => 10,
            ],
            [
                'first_name' => 'Francesco',
                'last_name' => 'Bagnaia',
                'birth_date' => '1997-01-14',
                'birth_country' => 'Italy',
                'vehicle_number' => 63,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/2ea90c6c-7b86-4430-bf20-9fb8761ef999/J7PRxOT5.png?height=700&width=800',
                'active' => true,
                'team_id' => 11,
            ],
            [
                'first_name' => 'Marc',
                'last_name' => 'Márquez',
                'birth_date' => '1993-02-17',
                'birth_country' => 'Spain',
                'vehicle_number' => 93,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/db39c323-167c-4a23-b3ae-75cfe6b06d95/jws78ATZ.png?height=700&width=800',
                'active' => true,
                'team_id' => 11,
            ],
            [
                'first_name' => 'Jorge',
                'last_name' => 'Martín',
                'birth_date' => '1998-01-29',
                'birth_country' => 'Spain',
                'vehicle_number' => 1,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/04/11/ab7fadd1-d2fa-41f7-a19d-833b0561f673/oE9Aa2VY.png?height=700&width=800',
                'active' => true,
                'team_id' => 12,
            ],
            [
                'first_name' => 'Marco',
                'last_name' => 'Bezzecchi',
                'birth_date' => '1998-11-12',
                'birth_country' => 'Italy',
                'vehicle_number' => 72,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/dbd5a0b9-f6c5-4fc8-86b5-546b05232429/5HcsbrNn.png?height=700&width=800',
                'active' => true,
                'team_id' => 12,
            ],
            [
                'first_name' => 'Fabio',
                'last_name' => 'Quartararo',
                'birth_date' => '1999-04-20',
                'birth_country' => 'France',
                'vehicle_number' => 20,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/6d108ca2-e4fc-4030-ab8d-69c481fcd666/DHp0R5id.png?height=700&width=800',
                'active' => true,
                'team_id' => 13,
            ],
            [
                'first_name' => 'Álex',
                'last_name' => 'Rins',
                'birth_date' => '1995-12-08',
                'birth_country' => 'Spain',
                'vehicle_number' => 42,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/5e238bf1-7951-4547-97c3-ec62c7af0c92/CxMFdBMs.png?height=700&width=800',
                'active' => true,
                'team_id' => 13,
            ],
            [
                'first_name' => 'Brad',
                'last_name' => 'Binder',
                'birth_date' => '1995-08-11',
                'birth_country' => 'South Africa',
                'vehicle_number' => 33,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/a2af759a-5879-47f1-b94c-2b9c48d01852/mjAvgii1.png?height=700&width=800',
                'active' => true,
                'team_id' => 14,
            ],
            [
                'first_name' => 'Pedro',
                'last_name' => 'Acosta',
                'birth_date' => '2004-05-25',
                'birth_country' => 'Spain',
                'vehicle_number' => 37,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/31931e59-0557-4f74-8fac-326c50dd9d60/I7CE3pUc.png?height=700&width=800',
                'active' => true,
                'team_id' => 14,
            ],
            [
                'first_name' => 'Maverick',
                'last_name' => 'Viñales',
                'birth_date' => '1995-01-12',
                'birth_country' => 'Spain',
                'vehicle_number' => 12,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/af0af1d5-a53c-47ee-988d-8ad6c37fe189/6PCFCrQu.png?height=700&width=800',
                'active' => true,
                'team_id' => 15,
            ],
            [
                'first_name' => 'Enea',
                'last_name' => 'Bastianini',
                'birth_date' => '1997-12-30',
                'birth_country' => 'Italy',
                'vehicle_number' => 23,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/cc91f6f5-00b2-468d-8bf0-587cb6e586ff/IYo43ylh.png?height=700&width=800',
                'active' => true,
                'team_id' => 15,
            ],
            [
                'first_name' => 'Jack',
                'last_name' => 'Miller',
                'birth_date' => '1995-01-18',
                'birth_country' => 'Australia',
                'vehicle_number' => 43,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/c1787ba0-46dd-4421-acc2-5b752cba4dd8/SNqHTjGK.png?height=700&width=800',
                'active' => true,
                'team_id' => 16,
            ],
            [
                'first_name' => 'Miguel',
                'last_name' => 'Oliveira',
                'birth_date' => '1995-01-04',
                'birth_country' => 'Portugal',
                'vehicle_number' => 88,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/04/10/45a86bfe-62cb-4332-9196-9db53d8147f6/3QFNaOUw.png?height=700&width=800',
                'active' => true,
                'team_id' => 16,
            ],
            [
                'first_name' => 'Álex',
                'last_name' => 'Márquez',
                'birth_date' => '1996-04-23',
                'birth_country' => 'Spain',
                'vehicle_number' => 73,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/28/6fff38e2-bd16-4cb0-ac20-3be9ee29ccd3/uzz61wfi.png?height=700&width=800',
                'active' => true,
                'team_id' => 17,
            ],
            [
                'first_name' => 'Fermín',
                'last_name' => 'Aldeguer',
                'birth_date' => '2005-04-05',
                'birth_country' => 'Spain',
                'vehicle_number' => 54,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/28/b9c97a6e-a729-44dc-bcc2-bfa861b092a8/zMpK9tLN.png?height=700&width=800',
                'active' => true,
                'team_id' => 17,
            ],
            [
                'first_name' => 'Fabio',
                'last_name' => 'Di Giannantonio',
                'birth_date' => '1998-10-10',
                'birth_country' => 'Italy',
                'vehicle_number' => 49,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/6ae96a17-d675-4dd9-b817-391bc4cd4555/CUaUtv2l.png?height=700&width=800',
                'active' => true,
                'team_id' => 18,
            ],
            [
                'first_name' => 'Franco',
                'last_name' => 'Morbidelli',
                'birth_date' => '1994-12-04',
                'birth_country' => 'Italy',
                'vehicle_number' => 21,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/a68a0e53-80b3-44b3-a5fe-ed245f817df4/Mxvp8G7i.png?height=700&width=800',
                'active' => true,
                'team_id' => 18,
            ],
            [
                'first_name' => 'Raúl',
                'last_name' => 'Fernández',
                'birth_date' => '2000-10-23',
                'birth_country' => 'Spain',
                'vehicle_number' => 25,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/1bcfb911-d846-4e2b-b759-f67046d2a722/tczdcKow.png?height=700&width=800',
                'active' => true,
                'team_id' => 19,
            ],
            [
                'first_name' => 'Ai',
                'last_name' => 'Ogura',
                'birth_date' => '2001-01-15',
                'birth_country' => 'Japan',
                'vehicle_number' => 79,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/03/14/8878f076-540a-4861-bde9-a748f72d9628/qBvY03bN.png?height=700&width=800',
                'active' => true,
                'team_id' => 19,
            ],
            [
                'first_name' => 'Johann',
                'last_name' => 'Zarco',
                'birth_date' => '1990-07-16',
                'birth_country' => 'France',
                'vehicle_number' => 5,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/4166e780-86ca-49d8-a42b-4627d26b1f48/I8FgpnEk.png?height=700&width=800',
                'active' => true,
                'team_id' => 20,
            ],
            [
                'first_name' => 'Somkiat',
                'last_name' => 'Chantra',
                'birth_date' => '1998-12-15',
                'birth_country' => 'Thailand',
                'vehicle_number' => 35,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/04/15/74366398-8165-4c76-9c5b-4704f939e11a/iJBqseXD.png?height=700&width=800',
                'active' => true,
                'team_id' => 20,
            ],
            [
                'first_name' => 'Luca',
                'last_name' => 'Marini',
                'birth_date' => '1997-08-10',
                'birth_country' => 'Italy',
                'vehicle_number' => 10,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/5ab75f09-d4bc-4f71-baf1-02007e3b5793/iDs8u21V.png?height=700&width=800',
                'active' => true,
                'team_id' => 21,
            ],
            [
                'first_name' => 'Joan',
                'last_name' => 'Mir',
                'birth_date' => '1997-09-01',
                'birth_country' => 'Spain',
                'vehicle_number' => 36,
                'profile_image' => 'https://resources.motogp.pulselive.com/photo-resources/2025/02/10/0475f8ae-5a34-4505-a49f-70fe912534ed/x5A64JfJ.png?height=700&width=800',    
                'active' => true,
                'team_id' => 21,
            ],    
        ];

        foreach ($drivers as $driver) {
            Driver::create($driver);
        }
    }
}
