<?php

namespace Database\Seeders;

use App\Models\Track;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;


class TrackSeeder extends Seeder
{
    public function run(): void
    {
            $tracks = [
                [
                    'id' => 1,
                    'name' => 'Albert Park Circuit',
                    'country' => 'Australia',
                    'location' => 'Melbourne',
                    'length' => 5.278,
                    'turns' => 14,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/2/27/Melbourne_GP_Circuit.png',
                ],
                [
                    'id' => 2,
                    'name' => 'Shanghai International Circuit',
                    'country' => 'China',
                    'location' => 'Shanghai',
                    'length' => 5.451,
                    'turns' => 16,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Shanghai_International_Racing_Circuit_track_map.svg',
                ],
                [
                    'id' => 3,
                    'name' => 'Bahrain International Circuit',
                    'country' => 'Bahrain',
                    'location' => 'Sakhir',
                    'length' => 5.412,
                    'turns' => 15,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Bahrain_International_Circuit--Grand_Prix_Layout.svg',
                ],
                [
                    'id' => 4,
                    'name' => 'Jeddah Street Circuit',
                    'country' => 'Saudi Arabia',
                    'location' => 'Jeddah',
                    'length' => 6.174,
                    'turns' => 27,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/b/be/Jeddah_Street_Circuit_2021.svg',
                ],
                [
                    'id' => 5,
                    'name' => 'Miami International Autodrome',
                    'country' => 'United States',
                    'location' => 'Miami',
                    'length' => 5.412,
                    'turns' => 19,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/2/24/Miami_Grand_Prix_layout_2022.svg',
                ],
                [
                    'id' => 6,
                    'name' => 'Imola Circuit',
                    'country' => 'Italy',
                    'location' => 'Imola',
                    'length' => 4.909,
                    'turns' => 19,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/4/47/Circuit_Imola_2009.svg',
                ],
                [
                    'id' => 7,
                    'name' => 'Circuit de Monaco',
                    'country' => 'Monaco',
                    'location' => 'Monte Carlo',
                    'length' => 3.337,
                    'turns' => 19,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Monte_Carlo_Formula_1_track_map.svg',
                ],
                [
                    'id' => 8,
                    'name' => 'Circuit de Barcelona-Catalunya',
                    'country' => 'Spain',
                    'location' => 'Montmeló',
                    'length' => 4.657,
                    'turns' => 16,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Circuit_de_Barcelona_Catalunya.svg',
                ],
                [
                    'id' => 9,
                    'name' => 'Circuit Gilles Villeneuve',
                    'country' => 'Canada',
                    'location' => 'Montreal',
                    'length' => 4.361,
                    'turns' => 14,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/1/11/Circuit_Gilles_Villeneuve.svg',
                ],
                [
                    'id' => 10,
                    'name' => 'Red Bull Ring',
                    'country' => 'Austria',
                    'location' => 'Spielberg',
                    'length' => 4.318,
                    'turns' => 10,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/8/88/Red_Bull_Ring.svg',
                ],
                [
                    'id' => 11,
                    'name' => 'Silverstone Circuit',
                    'country' => 'United Kingdom',
                    'location' => 'Silverstone',
                    'length' => 5.891,
                    'turns' => 18,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Silverstone_circuit_2020.svg',
                ],
                [
                    'id' => 12,
                    'name' => 'Circuit de Spa-Francorchamps',
                    'country' => 'Belgium',
                    'location' => 'Stavelot',
                    'length' => 7.004,
                    'turns' => 19,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Circuit_Spa.png',
                ],
                [
                    'id' => 13,
                    'name' => 'Hungaroring',
                    'country' => 'Hungary',
                    'location' => 'Budapest',
                    'length' => 4.381,
                    'turns' => 14,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/6/65/Hungaroring.svg',
                ],
                [
                    'id' => 14,
                    'name' => 'Circuit Zandvoort',
                    'country' => 'Netherlands',
                    'location' => 'Zandvoort',
                    'length' => 4.259,
                    'turns' => 14,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Circuit_Zandvoort_2020.svg',
                ],
                [
                    'id' => 15,
                    'name' => 'Monza Circuit',
                    'country' => 'Italy',
                    'location' => 'Monza',
                    'length' => 5.793,
                    'turns' => 11,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Circuit_Monza.svg',
                ],
                [
                    'id' => 16,
                    'name' => 'Baku City Circuit',
                    'country' => 'Azerbaijan',
                    'location' => 'Baku',
                    'length' => 6.003,
                    'turns' => 20,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Baku_city_circuit_track_map.svg',
                ],
                [
                    'id' => 17,
                    'name' => 'Marina Bay Street Circuit',
                    'country' => 'Singapore',
                    'location' => 'Singapore',
                    'length' => 4.928,
                    'turns' => 19,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/1/12/Marina_Bay_Street_Circuit_2023.svg',
                ],
                [
                    'id' => 18,
                    'name' => 'Suzuka Circuit',
                    'country' => 'Japan',
                    'location' => 'Suzuka',
                    'length' => 5.807,
                    'turns' => 18,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/9/96/Circuit_Suzuka.png',
                ],
                [
                    'id' => 19,
                    'name' => 'Circuit of the Americas',
                    'country' => 'United States',
                    'location' => 'Austin, Texas',
                    'length' => 5.513,
                    'turns' => 20,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Circuit_of_the_Americas.svg',
                ],
                [
                    'id' => 20,
                    'name' => 'Autódromo Hermanos Rodríguez',
                    'country' => 'Mexico',
                    'location' => 'Mexico City',
                    'length' => 4.304,
                    'turns' => 17,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Autodromo_Hermanos_Rodriguez_2022.svg',
                ],
                [
                    'id' => 21,
                    'name' => 'Interlagos (Autódromo José Carlos Pace)',
                    'country' => 'Brazil',
                    'location' => 'São Paulo',
                    'length' => 4.309,
                    'turns' => 15,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Interlagos.svg',
                ],
                [
                    'id' => 22,
                    'name' => 'Las Vegas Street Circuit',
                    'country' => 'United States',
                    'location' => 'Las Vegas',
                    'length' => 6.120,
                    'turns' => 17,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Las_Vegas_Grand_Prix_track_map.svg',
                ],
                [
                    'id' => 23,
                    'name' => 'Yas Marina Circuit',
                    'country' => 'United Arab Emirates',
                    'location' => 'Abu Dhabi',
                    'length' => 5.281,
                    'turns' => 16,
                    'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Yas_Marina_Circuit_2021.svg',
                ],
        ];

        foreach ($tracks as $track) {
            Track::create($track);
        }
    }
}